services:
  - type: web
    name: mycareer-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: CLIENT_URL
        value: https://mycareer-00.netlify.app
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: mycareer-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://mycareer-api.onrender.com/api
